baseURL: '/'
languageCode: ja
defaultContentLanguage: ja
publishDir: public
contentDir: content
title: OTTANXYZ
theme: languor
hasCJKLanguage: true
summaryLength: 150
canonifyURLs: true
disqusShortname: ottanxyz
paginate: 20
googleAnalytics: UA-54519352-1
rssLimit: 15
enableGitInfo: true
permalinks:
  posts: /posts/:year/:month/:slug
markup:
  highlight:
    style: github
params:
  author: ottanxyz
  favicon: images/favicon.ico
  twitter: 'https://twitter.com/ottanxyz/'
  facebook: 'https://www.facebook.com/ottanxyz/'
  github: 'https://github.com/ottanjp/'
  rss: 'https://ottan.xyz/index.xml'
  description: iPhone、Mac、Windows、ブログに関する様々なTips、トラブルシューティングをご紹介します
  locale: ja_JP
  fbappId: '808819212572711'
outputs:
  home: [HTML, JSON, RSS]
